FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy project configuration files
COPY my-turborepo/package.json my-turborepo/package-lock.json my-turborepo/turbo.json ./

# Copy the apps and packages directories
COPY my-turborepo/apps ./apps
COPY my-turborepo/packages ./packages

# Install dependencies
RUN npm install
RUN cd packages/db && npx prisma generate && cd ../..

# Build the project
RUN npm run build --filter=apps/web...

CMD ["npm", "run", "start-user-app"]
