FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy the main project configuration files
COPY package.json package-lock.json turbo.json ./

# Copy the apps and packages directories from my-turborepo
COPY my-turborepo/apps ./apps
COPY my-turborepo/packages ./packages

# Install dependencies
RUN npm install
RUN cd packages/db && npx prisma generate && cd ../..

# Build the project
RUN npm run build

CMD ["npm", "run", "start-user-app"]
